### ISSUE TITLE
Remove dependency on futures-util

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/futures-timer#39]
Right now we're pulling in quite a few dependencies through `futures-util-preview`. The only feature we're currently using that's included in it is `AtomicWaker`. I'm wondering if we may perhaps be able to drop this dep somehow.

cc/ @stjepang thoughts?

**Comment by stjepang** [comment]
As far as I can tell, only this is pulled in by `futures-timer`:

```
    ├── futures-timer v1.0.2
    │   ├── futures-core-preview v0.3.0-alpha.19 (*)
    │   ├── futures-util-preview v0.3.0-alpha.19
    │   │   ├── futures-core-preview v0.3.0-alpha.19 (*)
    │   │   ├── pin-utils v0.1.0-alpha.4 (*)
    │   │   └── slab v0.4.2
    │   └── pin-utils v0.1.0-alpha.4 (*)
```

So the `futures-util-preview` is not really adding much.

If need be, `AtomicWaker` is relatively simple and could be copied over into this repository.

**Comment by taiki-e** [comment]
> Right now we're pulling in quite a few dependencies through `futures-util-preview`.

FYI: I've made many dependencies of futures-util optional in https://github.com/rust-lang-nursery/futures-rs/pull/1709.

**Comment by yoshuawuyts** [comment]
@stjepang in terms of nested dependencies it isn't much; but we're essentially compiling all combinators twice right now: https://docs.rs/futures-util-preview/0.3.0-alpha.19/futures_util/

This seems like it would add up, and being able to shave it off seems relatively useful (:

**Comment by stjepang** [comment]
Let's try moving AtomicWaker here then. :)
